### PR TITLE
Is initialized

### PR DESCRIPTION
**Pull request by jalkjaer**
Add is_initialized function to test if lazy attribute is initialized -

### CODE REVIEW

**Comment by iyesin** [comment]
Hello @stefanholek,

Could you review this PR, please?

**Comment by stefanholek** [comment]
Hi Guys,

I see where you are coming from, and I may have led you on by giving that stupid caching example, but I don’t think lazy should go there.

Lazy is about deferred initialization of variables. It is not a cache, even though it can be used like one if the object is thrown away after use. Yes, there is lazy.invalidate() but that’s mainly because I need it for tests, and I probably should not have documented it even.

That said, I could be persuaded to expose the cached subclass, which currently lives in test_lazy.py, and add a cached.is_cached() API to it. This would cover your use-case without watering down the lazy contract.

Sounds good?

Stefan

**Comment by iyesin** [comment]
@stefanholek Sorry, but I don't get it. Why do you taking about caching? This PR is about adding one method `is_initialized` that gives a way to check if object was initialized already or not in runtime. Is it somehow wrong? If so, could you, please, explain?

**Comment by jalkjaer** [comment]
@stefanholek My main motivation was to be able to clean up resources that are lazily initialized - see my change to `store` example https://github.com/stefanholek/lazy/blob/bb4efa33c00ad9213d7a5687894861d60de5bb00/README.rst#examples

**Comment by stefanholek** [comment]
Apologies for all the work you did. Please use `if 'foo' in self.__dict__:` for your use case. I have added the `close` example to the README in lazy 1.6.

**Pull request closed without merging**
