### PR TITLE
Support type checking II

### PR DESCRIPTION
**Pull request by stefanholek**
This is @elKei24's PR #9 merged into the current main branch.

### CODE REVIEW

**Comment by stefanholek** [comment]
I seem to be unable to add you as reviewers to this pull request, so I'll try it this way: @elKei24 and @Palpatineli, please confirm that this branch works for you. Thank you!

**Review by elKei24 — APPROVED** [review]

**Comment by elKei24** [comment]
Works for me, thanks!

**Comment by stefanholek** [comment]
I found the typeshed stub for [cached_property](https://github.com/python/typeshed/blob/master/stdlib/functools.pyi#L142) and it looks like this:

```
class cached_property(Generic[_T]):
    @overload
    def __get__(self, instance: None, owner: type[Any] | None = ...) -> cached_property[_T]: ...
    @overload
    def __get__(self, instance: object, owner: type[Any] | None = ...) -> _T: ...
```

What I learned

* [Descriptors](https://docs.python.org/3/howto/descriptor.html#descriptor-protocol) can be invoked from a class (first case), from an instance (second case), and via `super()`.
* The `type` argument of `__get__` is indeed a [kwarg defaulting to None](https://docs.python.org/3/howto/descriptor.html#descriptor-protocol):

```
descr.__get__(self, obj, type=None) -> value
```

* [@overload](https://mypy.readthedocs.io/en/stable/more_types.html#function-overloading) allows to provide multiple type signatures for a function.
* Including the class ("_C") in the Generic makes it impossible to override lazy attributes in subclasses.

I am inclined to drop `TypeVar("_C")` and go with `Any` and `object` instead.

Like [this](https://github.com/stefanholek/lazy/blob/9d3af8c52965004d117176dcfa2021b1696de220/lazy/lazy.pyi).

**Comment by stefanholek** [comment]
This has been released as lazy 1.5. Thanks again for your help and patience.

**Pull request merged**
